name: Use Zero-Two Runner

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run on Zero-Two runner
        run: |
          echo "This is running on the Zero-Two runner in the Zero group"
